### ISSUE TITLE
Store pending challenges in a JSON file

### ISSUE THREAD

**Issue by szepeviktor** [candango/automatoes#21]
Could you write the details of the challenge to a JSON file?

I use a shell script
https://github.com/szepeviktor/debian-server-tools/blob/master/security/cert-update-manuale.sh#L106-L127
to move HTTP verification files in place, and it would be nice to have other types also in a machine readable format.
Thank you.

**Comment by piraz** [comment]
I'm creating an order to store orders: https://github.com/candango/automatoes/blob/cee544df19c2248d34e518c9370df41654df1a79/automatoes/model.py#L50-L66

The challenge is inside the order as you can see at https://tools.ietf.org/html/rfc8555#section-7.4.1 page 45.

```
{
     "status": "pending",
     "expires": "2016-01-05T14:09:07.99Z",

     "notBefore": "2016-01-01T00:00:00Z",
     "notAfter": "2016-01-08T00:00:00Z",

     "identifiers": [
       { "type": "dns", "value": "www.example.org" },
       { "type": "dns", "value": "example.org" }
     ],

     "authorizations": [
       "https://example.com/acme/authz/PAniVnsZcis",
       "https://example.com/acme/authz/r4HqLzrSrpI"
     ],

     "finalize": "https://example.com/acme/order/TOlocE8rfgo/finalize"
   }
```

What you do with the HTTP verification files?

**Comment by szepeviktor** [comment]
> What you do with the HTTP verification files?

my background script would create them in the document root of the webserver.

**Comment by szepeviktor** [comment]
my background script would also set DNS records!

**Comment by piraz** [comment]
Interesting... usually you do multiple domains right?

**Comment by piraz** [comment]
We can dump everything from the processing in the current or provided directory.

**Comment by szepeviktor** [comment]
No!
The expiration checker alerts me when I have to renew one of them
https://github.com/szepeviktor/debian-server-tools/blob/master/monitoring/cert-expiry.sh

I have ~20 clients.

**Comment by piraz** [comment]
So your workflow is one domain for key?

**Comment by szepeviktor** [comment]
Yes, usually staging.testdomain.com and dev.testdomain.com

**Comment by piraz** [comment]
We can generate *.domain.test also with ACME V2.

**Comment by szepeviktor** [comment]
Thank you.

wildcard certs are less safe than explicit ones.

**Comment by piraz** [comment]
Let's try to create the unstable 0.9.1 this year and we polish a better 0.9.2.

I'll see what kind of structure we can generate things and I'll let you know.

**Comment by szepeviktor** [comment]
Thank you.

**Comment by piraz** [comment]
I'll store pending challenges into the order directory.

The file format is <domain>_challenge.json.

The order directory is <current_directory>/orders/<domain(s)_hash>.

Domain(s)_hash is:

`domains_hash = hashlib.sha256("_".join(domains).encode('ascii')).hexdigest()`

I'll add a new command to output the hash. Something like:

```
> manuale hash domain1.com domain2.com.
3c93aa8afb7e2d4a8f26cb983ba69b8d84e4fd023434651fc59de408d476be35

> manuale authorize -v domain1.com domain2.com.
Candango Automatoes 0.9.0. Manuale replacement.


Orders path found at /home/fpiraz/source/candango/tmp/autotests/orders.
Current order 3c93aa8afb7e2d4a8f26cb983ba69b8d84e4fd023434651fc59de408d476be35 path not found creating it at orders path.

Authorizing domain1.com, domain2.com.

  Order file not found creating it.
  Requesting challenge for domain1.com.
    Creating challenge file domain1.com_challenge.json.

  Requesting challenge for domain2.com.
    Creating challenge file domain2.com_challenge.json.


  DNS verification required. Make sure these TXT records are in place:

    _acme-challenge.domain1.com.  IN TXT  "UdNKPlfCSwnX_S4n-Ry39Nk_Q1hMA9ZsshSyLAKZykA"
    _acme-challenge.domain2.com.  IN TXT  "SkjPIDdsPhaWZhpdPGyZLwVbrUVPXZHKPReoYjFUem0"

Press Enter to continue.
```

**Comment by piraz** [comment]
Here is an example:

File is ./orders/3c93aa8afb7e2d4a8f26cb983ba69b8d84e4fd023434651fc59de408d476be35/domain1.com_challenge.json

Format:
```
{
  "contents":
    {
      "type": "dns-01",
      "status": "pending",
      "url": "https://<server_addres>/acme/chall-v3/33949051101/a2-kdC",
      "token": "A_Cd6yOrM0nq7tI6M2QoOBosETWgg3ugRooWyuiuZIs" // This is used to create the file name when using http-1
    },
  "domain": "domain1.com",
  "expires": "2020-01-13T00:35:53Z",
  "status": "pending",
  "type": "dns",
  "key": "AdNKPlfCSwnX_C4n-Ry39Nk_Q2hMA0ZsshSyLAKZykA" // This is the challenge calculation value used in the TXT record for dns-1 or inside the http-1 file
}
```

The values presented in the file for contents.url, contents.token and key are not real.

**Comment by szepeviktor** [comment]
Thank you :)
