### ISSUE TITLE
Upgrade existent account from acme v1 to acme v2

### ISSUE THREAD

**Issue by piraz** [candango/automatoes#30]
The existent acme v1 account file is holding a different url from acme v2.

Let's fix that during the first run and set the account fixed.

**Comment by piraz** [comment]
If you need to fix just replace `https://acme-v01.api.letsencrypt.org/acme/reg/` to `https://acme-staging-v02.api.letsencrypt.org/acme/acct` in the account.json file.

**Comment by szepeviktor** [comment]
There is "staging" in the above URL.

**Comment by piraz** [comment]
Thank you, @szepeviktor. Fixed.

**Comment by szepeviktor** [comment]
Thank you.

**Comment by szepeviktor** [comment]
@piraz Please do release v0.9.2

**Comment by piraz** [comment]
Just with this?

**Comment by szepeviktor** [comment]
Yes.
A one-line changelog **is** a changelog.
Thanks.

**Comment by piraz** [comment]
Got it.

**Comment by szepeviktor** [comment]
We are very near to v1 shutdown :)

**Comment by piraz** [comment]
The build is broken. I'll fix it and publish 0.9.2.

I'll push other issues to 0.9.3.

**Comment by szepeviktor** [comment]
Thank you.
