### ISSUE TITLE
Revoke dies with AttributeError: 'str' object has no attribute 'public_bytes'

### ISSUE THREAD

**Issue by mc3** [candango/automatoes#34]
Issue a new cert:

Requesting certificate issuance...
  Certificate downloaded.
  Expires: 2020-05-18
   SHA256: 3feb10d0b9d23296d75874270c6807c987b03405ff42ba0839e0c1fcdf2852e9

  Wrote key to /var/pki_dev/development_CA_2/db/buildx.lrau.net.pem
  Wrote certificate to /var/pki_dev/development_CA_2/db/buildx.lrau.net.crt
  Wrote certificate with intermediate to /var/pki_dev/development_CA_2/db/buildx.lrau.net.chain.crt
  Wrote intermediate certificate to /var/pki_dev/development_CA_2/db/buildx.lrau.net.intermediate.crt

Then try to revoke it:

manuale revoke   buildx.lrau.net.crt
Candango Automatoes 0.9.0. Manuale replacement.

Are you sure you want to revoke this certificate? It includes the following domains:
  buildx.lrau.net
This can't be undone. Confirm? [y/N] y
Oops! An unhandled error occurred. Please file a bug.
'str' object has no attribute 'public_bytes'
Traceback (most recent call last):
  File "/usr/local/py_venv/pki_dev_p37/lib/python3.7/site-packages/automatoes/cli.py", line 324, in manuale_main
    args.func(args)
  File "/usr/local/py_venv/pki_dev_p37/lib/python3.7/site-packages/automatoes/cli.py", line 157, in _revoke
    certificate=args.certificate
  File "/usr/local/py_venv/pki_dev_p37/lib/python3.7/site-packages/automatoes/revoke.py", line 60, in revoke
    acme.revoke_certificate(export_certificate_for_acme(certificate))
  File "/usr/local/py_venv/pki_dev_p37/lib/python3.7/site-packages/automatoes/acme.py", line 462, in revoke_certificate
    'certificate':  export_certificate_for_acme(cert),
  File "/usr/local/py_venv/pki_dev_p37/lib/python3.7/site-packages/automatoes/crypto.py", line 228, in export_certificate_for_acme
    return jose_b64(cert.public_bytes(Encoding.DER))
AttributeError: 'str' object has no attribute 'public_bytes'

(pki_dev_p37) # python --version
Python 3.7.6
(pki_dev_p37) # pip list
Package       Version    Location                                    
------------- ---------- --------------------------------------------
asn1crypto    0.24.0     
automatoes    0.9.0      
bcrypt        3.1.6      
cartola       0.1        
certifi       2018.11.29 
cffi          1.12.1     
chardet       3.0.4      
cryptography  2.8        
idna          2.8        
iso8601       0.1.12     
paramiko      2.6.0      
pip           20.0.2     
prettytable   0.7.2      
py-postgresql 1.2.1      
pyasn1        0.4.5      
pycparser     2.19       
PyNaCl        1.3.0      
requests      2.22.0     
serverPKI     0.9.5      /usr/local/py_venv/pki_dev_p37/src/serverPKI
setuptools    40.6.3     
six           1.12.0     
urllib3       1.24.1     
wheel         0.32.3

**Comment by mc3** [comment]
This patch fixes it:
index 7ec7519..f568889 100644
--- a/automatoes/acme.py
+++ b/automatoes/acme.py
@@ -457,9 +457,9 @@ class AcmeV2(Acme):
             return response
         raise AcmeError(response)
 
-    def revoke_certificate(self, cert):
+    def revoke_certificate(self, cert_b64):
         response = self.post(self.url_from_directory('revokeCert'), {
-            'certificate':  export_certificate_for_acme(cert),
+            'certificate':  cert_b64,
         }, kid=self.account.uri)
         if response.status_code == 200:
             return response

**Comment by piraz** [comment]
> This patch fixes it:
> 
> ```
> index 7ec7519..f568889 100644
> --- a/automatoes/acme.py
> +++ b/automatoes/acme.py
> @@ -457,9 +457,9 @@ class AcmeV2(Acme):
>              return response
>          raise AcmeError(response)
>  
> -    def revoke_certificate(self, cert):
> +    def revoke_certificate(self, cert_b64):
>          response = self.post(self.url_from_directory('revokeCert'), {
> -            'certificate':  export_certificate_for_acme(cert),
> +            'certificate':  cert_b64,
>          }, kid=self.account.uri)
>          if response.status_code == 200:
>              return response
> ```

This fix will break tests. The export_certificate_for_acme conversion was moved into the AcmeV2 revoke method because so we can receive a bare certificate object and keep any acme internal operation and/or input handling inside the method. That would be better for a future SDK.

That was my mistake or I reverted revoke.py when I was publishing the first version.

I'll publish 0.9.1 tonight with the fix.

**Comment by piraz** [comment]
Published to pypi.
