### ISSUE TITLE
New command line option to control exit status

### ISSUE THREAD

**Issue by szepeviktor** [candango/automatoes#40]
There could be an `--exit-status` option or simply it could be the default behavior:
e.g. when authorization fails the exit status would be non-zero.

AFAIK now it is 0.

**Comment by piraz** [comment]
I think the exit status would be different if we have any issue during the transaction. Need to confirm.

I'll check the authorization error.

**Comment by piraz** [comment]
What was the command you ran that returned 0?

**Comment by szepeviktor** [comment]
`manuale authorize --method http $COMMON_NAME`

**Comment by piraz** [comment]
Is this returning 0? Do you have the error being printed?

**Comment by szepeviktor** [comment]
I'm sorry, I was wrong

```
$ manuale authorize --method http fizetes.voiz.hu
Candango Automatoes 0.9.1. Manuale replacement.


Authorizing fizetes.voiz.hu.

  Requesting challenge for fizetes.voiz.hu.

  HTTP verification required. Make sure these files are in place:

    http://fizetes.voiz.hu/.well-known/acme-challenge/OY_eUPit_77PXBfJQvTcCyOF84j2N_uqK3T2RlDSvIw

  The necessary files have been written to the current directory.


Press Enter to continue.

  fizetes.voiz.hu: waiting for verification. Checking in 5 seconds.
  fizetes.voiz.hu: The key authorization file from the server did not match this challenge "OY_eUPit_77PXBfJQvTcCyOF84j2N_uqK3T2RlDSvIw._VlinGiDYo836_oyddyWwRt4uPfxar2vsnL5mO7Gt2A" != "" (urn:ietf:params:acme:error:unauthorized)
  0 domain(s) authorized, 1 failed.
  Authorized: N/A
  Failed: fizetes.voiz.hu
  WARNING: The current order will be invalidated. Try again.
{'OY_eUPit_77PXBfJQvTcCyOF84j2N_uqK3T2RlDSvIw'}

$ echo $?
128
```

**Comment by piraz** [comment]
I'm using https://github.com/candango/cartola/blob/develop/cartola/sysexits.py to control.

Here are the source I got the codes: http://tldp.org/LDP/abs/html/exitcodes.html

In this code I have sysexits.EX_FATAL_ERROR, your case and sysexits.EX_CANNOT_EXECUTE. If goes trough it is sysexits.EX_OK that is 0.

On cli I need to get sysexits on because we have an except with 1, 2 and 3. I think we need better feed back.

So you can have 1,2,3 from cli and 126 and  128 from authorize.

**Comment by piraz** [comment]
On cli I agree with catch all that returns 1.

The one that gets the interruption is returning 2 is supposed to be 130(EX_TERMINATED_BY_CRTL_C).

The 3 is supposed to be 1 also so in that case when we have AutomatoesError that should be handled better, maybe EX_MISUSE that is 2 or EX_CONFIG that is 78.

For sure KeyboardInterrupt isn't 2 but 130, AutomatoesError isn't 1 if Exeption is 1.

I'll open a bug for that.

**Comment by szepeviktor** [comment]
Thank you for your response!
